var searchData=
[
  ['value_5ftype_29744',['value_type',['../d7/d46/struct_kratos_1_1_sparse_matrix_multiplication_utility_1_1value__type.html',1,'Kratos::SparseMatrixMultiplicationUtility']]],
  ['valuelogger_29745',['ValueLogger',['../de/dea/classloggers_1_1value__logger__base_1_1_value_logger.html',1,'loggers::value_logger_base']]],
  ['valueloggerbeadoptimization_29746',['ValueLoggerBeadOptimization',['../d7/d45/classloggers_1_1value__logger__bead__optimization_1_1_value_logger_bead_optimization.html',1,'loggers::value_logger_bead_optimization']]],
  ['valueloggergradientprojection_29747',['ValueLoggerGradientProjection',['../d8/d39/classloggers_1_1value__logger__gradient__projection_1_1_value_logger_gradient_projection.html',1,'loggers::value_logger_gradient_projection']]],
  ['valueloggerpenalizedprojection_29748',['ValueLoggerPenalizedProjection',['../d9/da1/classloggers_1_1value__logger__penalized__projection_1_1_value_logger_penalized_projection.html',1,'loggers::value_logger_penalized_projection']]],
  ['valueloggerrelaxedgradientprojection_29749',['ValueLoggerRelaxedGradientProjection',['../d1/d35/classloggers_1_1value__logger__relaxed__gradient__projection_1_1_value_logger_relaxed_gradient_projection.html',1,'loggers::value_logger_relaxed_gradient_projection']]],
  ['valueloggershapefractionoptimization_29750',['ValueLoggerShapeFractionOptimization',['../df/d8b/classloggers_1_1value__logger__shape__fraction__optimization_1_1_value_logger_shape_fraction_optimization.html',1,'loggers::value_logger_shape_fraction_optimization']]],
  ['valueloggersteepestdescent_29751',['ValueLoggerSteepestDescent',['../de/d88/classloggers_1_1value__logger__steepest__descent_1_1_value_logger_steepest_descent.html',1,'loggers::value_logger_steepest_descent']]],
  ['valueloggertrustregion_29752',['ValueLoggerTrustRegion',['../dd/dbc/classloggers_1_1value__logger__trust__region_1_1_value_logger_trust_region.html',1,'loggers::value_logger_trust_region']]],
  ['valuemessage_29753',['ValueMessage',['../dc/d7c/class_kratos_1_1_internals_1_1_value_message.html',1,'Kratos::Internals']]],
  ['valuemessage_3c_20bool_20_3e_29754',['ValueMessage&lt; bool &gt;',['../dc/d7c/class_kratos_1_1_internals_1_1_value_message.html',1,'Kratos::Internals']]],
  ['valuemessage_3c_20char_20_3e_29755',['ValueMessage&lt; char &gt;',['../dc/d7c/class_kratos_1_1_internals_1_1_value_message.html',1,'Kratos::Internals']]],
  ['valuemessage_3c_20double_20_3e_29756',['ValueMessage&lt; double &gt;',['../dc/d7c/class_kratos_1_1_internals_1_1_value_message.html',1,'Kratos::Internals']]],
  ['valuemessage_3c_20flags_3a_3ablocktype_20_3e_29757',['ValueMessage&lt; Flags::BlockType &gt;',['../dc/d7c/class_kratos_1_1_internals_1_1_value_message.html',1,'Kratos::Internals']]],
  ['valuemessage_3c_20int_20_3e_29758',['ValueMessage&lt; int &gt;',['../dc/d7c/class_kratos_1_1_internals_1_1_value_message.html',1,'Kratos::Internals']]],
  ['valuemessage_3c_20long_20unsigned_20int_20_3e_29759',['ValueMessage&lt; long unsigned int &gt;',['../dc/d7c/class_kratos_1_1_internals_1_1_value_message.html',1,'Kratos::Internals']]],
  ['valuemessage_3c_20unsigned_20int_20_3e_29760',['ValueMessage&lt; unsigned int &gt;',['../dc/d7c/class_kratos_1_1_internals_1_1_value_message.html',1,'Kratos::Internals']]],
  ['valuemethod_29761',['ValueMethod',['../d6/d35/class_kratos_1_1_temporal_methods_1_1_temporal_mean_method_1_1_value_method.html',1,'Kratos::TemporalMethods::TemporalMeanMethod&lt; TContainerType, TContainerItemType, TDataRetrievalFunctor, TDataStorageFunctor &gt;::ValueMethod&lt; TDataType &gt;'],['../d1/d54/class_kratos_1_1_temporal_methods_1_1_temporal_root_mean_square_method_1_1_value_method.html',1,'Kratos::TemporalMethods::TemporalRootMeanSquareMethod&lt; TContainerType, TContainerItemType, TDataRetrievalFunctor, TDataStorageFunctor &gt;::ValueMethod&lt; TDataType &gt;'],['../dd/d11/class_kratos_1_1_temporal_methods_1_1_temporal_sum_method_1_1_value_method.html',1,'Kratos::TemporalMethods::TemporalSumMethod&lt; TContainerType, TContainerItemType, TDataRetrievalFunctor, TDataStorageFunctor &gt;::ValueMethod&lt; TDataType &gt;'],['../d3/d00/class_kratos_1_1_temporal_methods_1_1_temporal_variance_method_1_1_value_method.html',1,'Kratos::TemporalMethods::TemporalVarianceMethod&lt; TContainerType, TContainerItemType, TDataRetrievalFunctor, TDataStorageFunctor &gt;::ValueMethod&lt; TDataType &gt;']]],
  ['vangenuchtenlaw_29762',['VanGenuchtenLaw',['../de/da1/class_van_genuchten_law.html',1,'']]],
  ['variable_29763',['Variable',['../d1/d66/class_kratos_1_1_variable.html',1,'Kratos']]],
  ['variable_3c_20double_20_3e_29764',['Variable&lt; double &gt;',['../d1/d66/class_kratos_1_1_variable.html',1,'Kratos']]],
  ['variable_3c_20gradientdatatype_20_3e_29765',['Variable&lt; GradientDataType &gt;',['../d1/d66/class_kratos_1_1_variable.html',1,'Kratos']]],
  ['variable_3c_20int_20_3e_29766',['Variable&lt; int &gt;',['../d1/d66/class_kratos_1_1_variable.html',1,'Kratos']]],
  ['variable_3c_20kratos_3a_3aarray_5f1d_3c_20double_2c_203_20_3e_20_3e_29767',['Variable&lt; Kratos::array_1d&lt; double, 3 &gt; &gt;',['../d1/d66/class_kratos_1_1_variable.html',1,'Kratos']]],
  ['variable_3c_20kratos_3a_3ainternals_3a_3amatrix_20_3e_29768',['Variable&lt; Kratos::Internals::Matrix &gt;',['../d1/d66/class_kratos_1_1_variable.html',1,'Kratos']]],
  ['variable_3c_20tvalue_20_3e_29769',['Variable&lt; TValue &gt;',['../d1/d66/class_kratos_1_1_variable.html',1,'Kratos']]],
  ['variable_3c_20tvartype_20_3e_29770',['Variable&lt; TVarType &gt;',['../d1/d66/class_kratos_1_1_variable.html',1,'Kratos']]],
  ['variable_5fplotter_29771',['variable_plotter',['../d7/de9/classplot__variables_1_1variable__plotter.html',1,'plot_variables']]],
  ['variablechecker_29772',['VariableChecker',['../d1/d07/class_kratos_1_1_python_1_1_variable_checker.html',1,'Kratos::Python']]],
  ['variablecomparator_29773',['VariableComparator',['../d4/d5c/struct_kratos_1_1_variable_comparator.html',1,'Kratos']]],
  ['variablecreator_29774',['VariableCreator',['../da/d2a/classclasses_1_1variable_creator_1_1_variable_creator.html',1,'classes::variableCreator']]],
  ['variablecreator3d_29775',['VariableCreator3D',['../d0/d03/classclasses_1_1variable_creator_1_1_variable_creator3_d.html',1,'classes::variableCreator']]],
  ['variabledatabase_29776',['VariableDatabase',['../dd/d11/class_kratos_1_1_variable_database.html',1,'Kratos']]],
  ['variabledatacollector_29777',['VariableDataCollector',['../dc/da5/class_kratos_1_1_line_output_process_utilities_1_1_variable_data_collector.html',1,'Kratos::LineOutputProcessUtilities']]],
  ['variablederivatives_29778',['VariableDerivatives',['../db/dd5/class_kratos_1_1_q_s_v_m_s_residual_derivatives_1_1_variable_derivatives.html',1,'Kratos::QSVMSResidualDerivatives']]],
  ['variablehasher_29779',['VariableHasher',['../d7/df9/struct_kratos_1_1_variable_hasher.html',1,'Kratos']]],
  ['variableindexingpython_29780',['VariableIndexingPython',['../db/d39/class_kratos_1_1_python_1_1_variable_indexing_python.html',1,'Kratos::Python']]],
  ['variableio_29781',['VariableIO',['../d8/dbb/classcore_1_1operations_1_1model__part_1_1_variable_i_o.html',1,'core::operations::model_part']]],
  ['variableslistdatavaluecontainer_29782',['VariablesListDataValueContainer',['../d6/d9e/class_variables_list_data_value_container.html',1,'']]],
  ['variablesmanager_29783',['VariablesManager',['../dc/d41/classvariables__management_1_1_variables_manager.html',1,'variables_management']]],
  ['variableutils_29784',['VariableUtils',['../d3/dc4/class_variable_utils.html',1,'']]],
  ['variablevectorretriever_29785',['VariableVectorRetriever',['../d2/dea/struct_kratos_1_1_variable_vector_retriever.html',1,'Kratos']]],
  ['variancesampler_29786',['VarianceSampler',['../d2/df5/class_kratos_1_1_variance_sampler.html',1,'Kratos']]],
  ['variationaldistancecalculationprocess_29787',['VariationalDistanceCalculationProcess',['../d7/deb/class_kratos_1_1_variational_distance_calculation_process.html',1,'Kratos']]],
  ['variationvariables_29788',['VariationVariables',['../dd/de0/struct_kratos_1_1_shell5p_element_1_1_variation_variables.html',1,'Kratos::Shell5pElement']]],
  ['vector3_29789',['Vector3',['../d5/d7c/class_c_sharp_kratos_wrapper_1_1_vector3.html',1,'CSharpKratosWrapper']]],
  ['vectoraveragesampler_29790',['VectorAverageSampler',['../df/d4d/class_kratos_1_1_vector_average_sampler.html',1,'Kratos']]],
  ['vectorfield_29791',['VectorField',['../dc/d2f/class_kratos_1_1_vector_field.html',1,'Kratos']]],
  ['vectorfield_3c_203_20_3e_29792',['VectorField&lt; 3 &gt;',['../dc/d2f/class_kratos_1_1_vector_field.html',1,'Kratos']]],
  ['vectorgaussianrandomfield_29793',['VectorGaussianRandomField',['../dc/dac/class_gaussian_random_field_1_1_vector_gaussian_random_field.html',1,'GaussianRandomField']]],
  ['vectorindexcomparor_29794',['VectorIndexComparor',['../d3/dc1/struct_kratos_1_1_vector_index_comparor.html',1,'Kratos']]],
  ['vectorindexhasher_29795',['VectorIndexHasher',['../d8/d86/struct_kratos_1_1_vector_index_hasher.html',1,'Kratos']]],
  ['vectormessage_29796',['VectorMessage',['../d8/ddf/class_kratos_1_1_internals_1_1_vector_message.html',1,'Kratos::Internals']]],
  ['vectormessage_3c_20valuetype_20_3e_29797',['VectorMessage&lt; ValueType &gt;',['../d8/ddf/class_kratos_1_1_internals_1_1_vector_message.html',1,'Kratos::Internals']]],
  ['velocitybossakadjointscheme_29798',['VelocityBossakAdjointScheme',['../da/ddd/class_kratos_1_1_velocity_bossak_adjoint_scheme.html',1,'Kratos']]],
  ['velocitybossaksensitivitybuilderscheme_29799',['VelocityBossakSensitivityBuilderScheme',['../d6/d4c/class_kratos_1_1_velocity_bossak_sensitivity_builder_scheme.html',1,'Kratos']]],
  ['velocityderivative_29800',['VelocityDerivative',['../da/d34/class_kratos_1_1_q_s_v_m_s_derivative_utilities_1_1_velocity_derivative.html',1,'Kratos::QSVMSDerivativeUtilities']]],
  ['velocityenrichedpfem22d_29801',['VelocityEnrichedPFEM22D',['../d5/d04/class_kratos_1_1_velocity_enriched_p_f_e_m22_d.html',1,'Kratos']]],
  ['velocitypressurenormsquareresponsefunction_29802',['VelocityPressureNormSquareResponseFunction',['../d9/d25/class_kratos_1_1_velocity_pressure_norm_square_response_function.html',1,'Kratos']]],
  ['velocityverletsolverstrategy_29803',['VelocityVerletSolverStrategy',['../d5/dc0/class_kratos_1_1_velocity_verlet_solver_strategy.html',1,'Kratos']]],
  ['vertexcontaineriotrampoline_29804',['VertexContainerIOTrampoline',['../dc/da1/class_kratos_1_1_python_1_1_vertex_container_i_o_trampoline.html',1,'Kratos::Python']]],
  ['viscousgeneralizedkelvin_29805',['ViscousGeneralizedKelvin',['../d8/db0/class_viscous_generalized_kelvin.html',1,'']]],
  ['viscousgeneralizedmaxwell_29806',['ViscousGeneralizedMaxwell',['../d5/dfe/class_viscous_generalized_maxwell.html',1,'']]],
  ['visualizationmeshprocess_29807',['VisualizationMeshProcess',['../d9/dcb/classvisualization__mesh__process_1_1_visualization_mesh_process.html',1,'visualization_mesh_process']]],
  ['visualizationutilities_29808',['VisualizationUtilities',['../d1/dc9/class_kratos_1_1_visualization_utilities.html',1,'Kratos']]],
  ['vms_29809',['VMS',['../d4/de8/class_kratos_1_1_v_m_s.html',1,'Kratos']]],
  ['vms_3c_20tdim_2c_20tdim_2b1_20_3e_29810',['VMS&lt; TDim, TDim+1 &gt;',['../d4/de8/class_kratos_1_1_v_m_s.html',1,'Kratos']]],
  ['vmsmonolithickbasedwallcondition_29811',['VMSMonolithicKBasedWallCondition',['../de/dc4/class_kratos_1_1_v_m_s_monolithic_k_based_wall_condition.html',1,'Kratos']]],
  ['volumeaveragingtool_29812',['VolumeAveragingTool',['../dd/df5/class_kratos_1_1_volume_averaging_tool.html',1,'Kratos']]],
  ['volumerecoveryprocess_29813',['VolumeRecoveryProcess',['../d3/d99/classvolume__recovery__process_1_1_volume_recovery_process.html',1,'volume_recovery_process']]],
  ['volumeshapingprocess_29814',['VolumeShapingProcess',['../d7/dd2/class_kratos_1_1_volume_shaping_process.html',1,'Kratos::VolumeShapingProcess'],['../d5/d81/classvolume__shaping__process_1_1_volume_shaping_process.html',1,'volume_shaping_process.VolumeShapingProcess']]],
  ['vonkarmancovariance_29815',['VonKarmanCovariance',['../dd/d55/class_covariance_kernels_1_1_von_karman_covariance.html',1,'CovarianceKernels']]],
  ['vonmisesplasticpotential_29816',['VonMisesPlasticPotential',['../da/d94/class_kratos_1_1_von_mises_plastic_potential.html',1,'Kratos']]],
  ['vonmisesyieldsurface_29817',['VonMisesYieldSurface',['../d9/d99/class_kratos_1_1_von_mises_yield_surface.html',1,'Kratos']]],
  ['vorticityrecoverer_29818',['VorticityRecoverer',['../d2/df5/classderivative__recovery_1_1recoverer_1_1_vorticity_recoverer.html',1,'derivative_recovery::recoverer']]],
  ['vorticityutilities_29819',['VorticityUtilities',['../d6/d42/class_kratos_1_1_vorticity_utilities.html',1,'Kratos']]],
  ['vpstrategy_29820',['VPStrategy',['../db/db7/class_kratos_1_1_v_p_strategy.html',1,'Kratos']]],
  ['vtkoutput_29821',['VtkOutput',['../db/d7e/classdem__vtk__output_1_1_vtk_output.html',1,'dem_vtk_output']]],
  ['vtkoutputprocess_29822',['VtkOutputProcess',['../d1/d89/classvtk__output__process_1_1_vtk_output_process.html',1,'vtk_output_process']]]
];
