var searchData=
[
  ['damaddedmassconditionprocess_27152',['DamAddedMassConditionProcess',['../dc/dab/class_kratos_1_1_dam_added_mass_condition_process.html',1,'Kratos']]],
  ['damagedplusdminusmasonry2dlaw_27153',['DamageDPlusDMinusMasonry2DLaw',['../d8/d93/class_damage_d_plus_d_minus_masonry2_d_law.html',1,'']]],
  ['damagedplusdminusmasonry3dlaw_27154',['DamageDPlusDMinusMasonry3DLaw',['../d2/ddd/class_damage_d_plus_d_minus_masonry3_d_law.html',1,'']]],
  ['damagemodel_27155',['DamageModel',['../da/db6/class_kratos_1_1_damage_model.html',1,'Kratos']]],
  ['damagemodel_3c_20linearelasticmodel_2c_20simojuyieldsurface_3c_20modifiedexponentialdamagehardeningrule_20_3e_20_3e_27156',['DamageModel&lt; LinearElasticModel, SimoJuYieldSurface&lt; ModifiedExponentialDamageHardeningRule &gt; &gt;',['../da/db6/class_kratos_1_1_damage_model.html',1,'Kratos']]],
  ['damagetonodesprocess_27157',['DamageToNodesProcess',['../d8/d9d/class_kratos_1_1_damage_to_nodes_process.html',1,'Kratos']]],
  ['damanalysis_27158',['DamAnalysis',['../d5/d66/classdam__analysis_1_1_dam_analysis.html',1,'dam_analysis']]],
  ['damazenhaheatfluxprocess_27159',['DamAzenhaHeatFluxProcess',['../df/d85/class_kratos_1_1_dam_azenha_heat_flux_process.html',1,'Kratos']]],
  ['dambofangconditiontemperatureprocess_27160',['DamBofangConditionTemperatureProcess',['../d7/deb/class_kratos_1_1_dam_bofang_condition_temperature_process.html',1,'Kratos']]],
  ['dambreakbenchmark_27161',['DamBreakBenchmark',['../d7/d5a/classdam__break__benchmark_1_1_dam_break_benchmark.html',1,'dam_break_benchmark']]],
  ['dambreakmodeler_27162',['DamBreakModeler',['../d0/d15/classdam__break__modeler_1_1_dam_break_modeler.html',1,'dam_break_modeler']]],
  ['damchemomechanicalagingyoungprocess_27163',['DamChemoMechanicalAgingYoungProcess',['../db/dc9/class_kratos_1_1_dam_chemo_mechanical_aging_young_process.html',1,'Kratos']]],
  ['damconstructionutility_27164',['DamConstructionUtility',['../d1/dde/classdam__construction__utility_1_1_dam_construction_utility.html',1,'dam_construction_utility']]],
  ['dameigensolver_27165',['DamEigenSolver',['../da/d4a/classdam__eigen__solver_1_1_dam_eigen_solver.html',1,'dam_eigen_solver']]],
  ['damfixtemperatureconditionprocess_27166',['DamFixTemperatureConditionProcess',['../d4/d50/class_kratos_1_1_dam_fix_temperature_condition_process.html',1,'Kratos']]],
  ['damgroutingreferencetemperatureprocess_27167',['DamGroutingReferenceTemperatureProcess',['../d6/d6d/class_kratos_1_1_dam_grouting_reference_temperature_process.html',1,'Kratos']]],
  ['damhydroconditionloadprocess_27168',['DamHydroConditionLoadProcess',['../d1/d93/class_kratos_1_1_dam_hydro_condition_load_process.html',1,'Kratos']]],
  ['daminputtablenodalyoungmodulusprocess_27169',['DamInputTableNodalYoungModulusProcess',['../d4/d1b/class_kratos_1_1_dam_input_table_nodal_young_modulus_process.html',1,'Kratos']]],
  ['dammechanicalsolver_27170',['DamMechanicalSolver',['../d6/dcd/classdam__mechanical__solver_1_1_dam_mechanical_solver.html',1,'dam_mechanical_solver']]],
  ['damnodalreferencetemperatureprocess_27171',['DamNodalReferenceTemperatureProcess',['../dd/dc9/class_kratos_1_1_dam_nodal_reference_temperature_process.html',1,'Kratos']]],
  ['damnodalyoungmodulusprocess_27172',['DamNodalYoungModulusProcess',['../de/d36/class_kratos_1_1_dam_nodal_young_modulus_process.html',1,'Kratos']]],
  ['damnoorzaiheatfluxprocess_27173',['DamNoorzaiHeatFluxProcess',['../df/d74/class_kratos_1_1_dam_noorzai_heat_flux_process.html',1,'Kratos']]],
  ['dampscheme_27174',['DamPScheme',['../d0/dc0/class_kratos_1_1_dam_p_scheme.html',1,'Kratos']]],
  ['damrandomfieldsvariableprocess_27175',['DamRandomFieldsVariableProcess',['../dc/d75/class_kratos_1_1_dam_random_fields_variable_process.html',1,'Kratos']]],
  ['damreservoirconstanttemperatureprocess_27176',['DamReservoirConstantTemperatureProcess',['../d1/d4e/class_kratos_1_1_dam_reservoir_constant_temperature_process.html',1,'Kratos']]],
  ['damreservoirmonitoringtemperatureprocess_27177',['DamReservoirMonitoringTemperatureProcess',['../df/dc3/class_kratos_1_1_dam_reservoir_monitoring_temperature_process.html',1,'Kratos']]],
  ['damselfweightsolver_27178',['DamSelfweightSolver',['../d4/dd6/classdam__selfweight__solver_1_1_dam_selfweight_solver.html',1,'dam_selfweight_solver']]],
  ['damtemperaturebydeviceprocess_27179',['DamTemperaturebyDeviceProcess',['../d0/d9e/class_kratos_1_1_dam_temperatureby_device_process.html',1,'Kratos']]],
  ['damthermomechanicsolver_27180',['DamThermoMechanicSolver',['../dc/d6b/classdam__thermo__mechanic__solver_1_1_dam_thermo_mechanic_solver.html',1,'dam_thermo_mechanic_solver']]],
  ['damtsolairheatfluxprocess_27181',['DamTSolAirHeatFluxProcess',['../d6/d11/class_kratos_1_1_dam_t_sol_air_heat_flux_process.html',1,'Kratos']]],
  ['damupliftcircularconditionloadprocess_27182',['DamUpliftCircularConditionLoadProcess',['../df/d42/class_kratos_1_1_dam_uplift_circular_condition_load_process.html',1,'Kratos']]],
  ['damupliftconditionloadprocess_27183',['DamUpliftConditionLoadProcess',['../da/d2a/class_kratos_1_1_dam_uplift_condition_load_process.html',1,'Kratos']]],
  ['damupmechanicalsolver_27184',['DamUPMechanicalSolver',['../df/d0e/classdam___u_p__mechanical__solver_1_1_dam_u_p_mechanical_solver.html',1,'dam_UP_mechanical_solver']]],
  ['damupscheme_27185',['DamUPScheme',['../d2/da8/class_kratos_1_1_dam_u_p_scheme.html',1,'Kratos']]],
  ['damupsolver_27186',['DamUPSolver',['../dc/d1e/classdam___p__solver_1_1_dam_u_p_solver.html',1,'dam_P_solver']]],
  ['damupthermomechanicsolver_27187',['DamUPThermoMechanicSolver',['../de/d77/classdam___u_p__thermo__mechanic__solver_1_1_dam_u_p_thermo_mechanic_solver.html',1,'dam_UP_thermo_mechanic_solver']]],
  ['damwestergaardconditionloadprocess_27188',['DamWestergaardConditionLoadProcess',['../db/d5f/class_kratos_1_1_dam_westergaard_condition_load_process.html',1,'Kratos']]],
  ['databuffers_27189',['DataBuffers',['../d9/d9a/struct_kratos_1_1_python_1_1_co_sim_i_o___wrappers_1_1_data_buffers.html',1,'Kratos::Python::CoSimIO_Wrappers']]],
  ['datadifferenceresidual_27190',['DataDifferenceResidual',['../d3/d14/classconvergence__accelerators_1_1convergence__accelerator__wrapper_1_1_data_difference_residual.html',1,'convergence_accelerators::convergence_accelerator_wrapper']]],
  ['dataitem_27191',['DataItem',['../d5/d8b/classcore_1_1xdmf_1_1_data_item.html',1,'core::xdmf']]],
  ['datalogger_27192',['DataLogger',['../da/d6c/classloggers_1_1data__logger__factory_1_1_data_logger.html',1,'loggers::data_logger_factory']]],
  ['dconvectiondiffusionexplicit_27193',['DConvectionDiffusionExplicit',['../d6/d56/class_kratos_1_1_d_convection_diffusion_explicit.html',1,'Kratos']]],
  ['deactivateconditionsoninactiveelements_27194',['DeactivateConditionsOnInactiveElements',['../d5/de0/class_deactivate_conditions_on_inactive_elements.html',1,'']]],
  ['decompressedmaterialbtstest_27195',['DecompressedMaterialBTSTest',['../d0/db7/classdecompressed__material__bts__test_1_1_decompressed_material_b_t_s_test.html',1,'decompressed_material_bts_test.DecompressedMaterialBTSTest'],['../d2/daa/classdecompressed__material__triaxials__and__bts__tests_1_1_decompressed_material_b_t_s_test.html',1,'decompressed_material_triaxials_and_bts_tests.DecompressedMaterialBTSTest']]],
  ['decompressedmaterialtriaxialtest_27196',['DecompressedMaterialTriaxialTest',['../d1/d17/classdecompressed__material__triaxial__test_1_1_decompressed_material_triaxial_test.html',1,'decompressed_material_triaxial_test.DecompressedMaterialTriaxialTest'],['../d6/d47/classdecompressed__material__triaxials__and__bts__tests_1_1_decompressed_material_triaxial_test.html',1,'decompressed_material_triaxials_and_bts_tests.DecompressedMaterialTriaxialTest']]],
  ['defaultcontroller_27197',['DefaultController',['../d2/d60/classcore_1_1controllers_1_1_default_controller.html',1,'core::controllers']]],
  ['defineembeddedwakeprocess_27198',['DefineEmbeddedWakeProcess',['../df/d56/classdefine__embedded__wake__process__2d_1_1_define_embedded_wake_process.html',1,'define_embedded_wake_process_2d']]],
  ['definewakeprocess_27199',['DefineWakeProcess',['../d6/da1/classdefine__wake__process_1_1_define_wake_process.html',1,'define_wake_process']]],
  ['definewakeprocess2d_27200',['DefineWakeProcess2D',['../d2/d7a/classdefine__wake__process__2d_1_1_define_wake_process2_d.html',1,'define_wake_process_2d']]],
  ['definewakeprocess3d_27201',['DefineWakeProcess3D',['../dd/dc0/classdefine__wake__process__3d_1_1_define_wake_process3_d.html',1,'define_wake_process_3d']]],
  ['deflatedcgsolver_27202',['DeflatedCGSolver',['../d5/d31/class_kratos_1_1_deflated_c_g_solver.html',1,'Kratos']]],
  ['deflationutils_27203',['DeflationUtils',['../d0/dbf/class_kratos_1_1_deflation_utils.html',1,'Kratos']]],
  ['deletemodelpartsmodeler_27204',['DeleteModelPartsModeler',['../dd/d64/classdelete__model__parts__modeler_1_1_delete_model_parts_modeler.html',1,'delete_model_parts_modeler']]],
  ['deleteoldh5files_27205',['DeleteOldH5Files',['../d3/d15/classcore_1_1operations_1_1system_1_1_delete_old_h5_files.html',1,'core::operations::system']]],
  ['deltatimeparameters_27206',['DeltaTimeParameters',['../d2/de4/struct_kratos_1_1_explicit_central_differences_scheme_1_1_delta_time_parameters.html',1,'Kratos::ExplicitCentralDifferencesScheme&lt; TSparseSpace, TDenseSpace &gt;::DeltaTimeParameters'],['../d7/d98/struct_kratos_1_1_explicit_hamilton_scheme_1_1_delta_time_parameters.html',1,'Kratos::ExplicitHamiltonScheme&lt; TSparseSpace, TDenseSpace &gt;::DeltaTimeParameters'],['../d2/ddb/struct_kratos_1_1_explicit_multi_stage_kim_scheme_1_1_delta_time_parameters.html',1,'Kratos::ExplicitMultiStageKimScheme&lt; TSparseSpace, TDenseSpace &gt;::DeltaTimeParameters']]],
  ['dem_5ffor_5fcoupling_5fsolution_27207',['DEM_for_coupling_Solution',['../de/d61/class_main_d_e_m__for__coupling_1_1_d_e_m__for__coupling___solution.html',1,'MainDEM_for_coupling']]],
  ['dem_5finlet_5fprocess_27208',['DEM_Inlet_Process',['../d5/d22/class_d_e_m__inlet__process_1_1_d_e_m___inlet___process.html',1,'DEM_inlet_process']]],
  ['demafterremeshidentificatorprocess_27209',['DemAfterRemeshIdentificatorProcess',['../dc/dca/class_kratos_1_1_dem_after_remesh_identificator_process.html',1,'Kratos']]],
  ['demanalysisstage_27210',['DEMAnalysisStage',['../dd/d91/class_d_e_m__analysis__stage_1_1_d_e_m_analysis_stage.html',1,'DEM_analysis_stage']]],
  ['demanalysisstagewithflush_27211',['DEMAnalysisStageWithFlush',['../d2/da8/class_kratos_d_e_m_analysis_1_1_d_e_m_analysis_stage_with_flush.html',1,'KratosDEMAnalysis.DEMAnalysisStageWithFlush'],['../dc/d42/class_main_kratos_thermal_d_e_m_analysis_1_1_d_e_m_analysis_stage_with_flush.html',1,'MainKratosThermalDEMAnalysis.DEMAnalysisStageWithFlush']]],
  ['dembenchmarksanalysisstage_27212',['DEMBenchmarksAnalysisStage',['../d3/d15/class_d_e_m__benchmarks__analysis_1_1_d_e_m_benchmarks_analysis_stage.html',1,'DEM_benchmarks_analysis']]],
  ['demcontact_27213',['DemContact',['../d4/d5c/class_kratos_1_1_dem_contact.html',1,'Kratos']]],
  ['demcoupledfluiddynamicsanalysis_27214',['DEMCoupledFluidDynamicsAnalysis',['../dd/d98/class_d_e_m__coupled__fluid__dynamics__analysis_1_1_d_e_m_coupled_fluid_dynamics_analysis.html',1,'DEM_coupled_fluid_dynamics_analysis']]],
  ['demcoupledpfemfluiddynamicsanalysis_27215',['DEMCoupledPFEMFluidDynamicsAnalysis',['../dd/d5b/class_d_e_m__coupled__pfem__fluid__dynamics__analysis_1_1_d_e_m_coupled_p_f_e_m_fluid_dynamics_analysis.html',1,'DEM_coupled_pfem_fluid_dynamics_analysis']]],
  ['demenergycalculator_27216',['DEMEnergyCalculator',['../d0/def/class_d_e_m__procedures_1_1_d_e_m_energy_calculator.html',1,'DEM_procedures.DEMEnergyCalculator'],['../d4/d42/class_d_e_m__procedures__mpi_1_1_d_e_m_energy_calculator.html',1,'DEM_procedures_mpi.DEMEnergyCalculator']]],
  ['demfemprocedures_27217',['DEMFEMProcedures',['../d6/d8b/class_d_e_m__procedures_1_1_d_e_m_f_e_m_procedures.html',1,'DEM_procedures.DEMFEMProcedures'],['../d4/dc3/class_d_e_m__procedures__mpi_1_1_d_e_m_f_e_m_procedures.html',1,'DEM_procedures_mpi.DEMFEMProcedures']]],
  ['demflags_27218',['DEMFlags',['../d0/d83/class_kratos_1_1_d_e_m_flags.html',1,'Kratos']]],
  ['demio_27219',['DEMIo',['../dd/db9/class_d_e_m__procedures_1_1_d_e_m_io.html',1,'DEM_procedures.DEMIo'],['../d6/d8f/class_d_e_m__procedures__mpi_1_1_d_e_m_io.html',1,'DEM_procedures_mpi.DEMIo'],['../d3/dc4/class_d_e_m__procedures__mpi__no__partitions_1_1_d_e_m_io.html',1,'DEM_procedures_mpi_no_partitions.DEMIo']]],
  ['demporomechanicscouplingsolver_27220',['DemPoroMechanicsCouplingSolver',['../dc/d52/classdem__poromechanics__coupling__analysis__stage_1_1_dem_poro_mechanics_coupling_solver.html',1,'dem_poromechanics_coupling_analysis_stage']]],
  ['demrestartutility_27221',['DEMRestartUtility',['../d8/d41/class_d_e_m__restart__utility_1_1_d_e_m_restart_utility.html',1,'DEM_restart_utility']]],
  ['demsaverestartprocess_27222',['DEMSaveRestartProcess',['../d2/d21/class_d_e_m__save__restart__process_1_1_d_e_m_save_restart_process.html',1,'DEM_save_restart_process']]],
  ['demsearch_27223',['DEMSearch',['../db/da5/class_kratos_1_1_d_e_m_search.html',1,'Kratos']]],
  ['demsearch_3c_20omp_5fdemsearch_20_3e_27224',['DEMSearch&lt; OMP_DEMSearch &gt;',['../db/da5/class_kratos_1_1_d_e_m_search.html',1,'Kratos']]],
  ['demsearchutilities_27225',['DemSearchUtilities',['../df/de0/class_kratos_1_1_dem_search_utilities.html',1,'Kratos']]],
  ['demstructurescouplingflags_27226',['DemStructuresCouplingFlags',['../d0/d3c/class_kratos_1_1_dem_structures_coupling_flags.html',1,'Kratos']]],
  ['demstructurescouplinggidoutput_27227',['DemStructuresCouplingGiDOutput',['../da/dfb/classdem__structures__coupling__gid__output_1_1_dem_structures_coupling_gi_d_output.html',1,'dem_structures_coupling_gid_output']]],
  ['demstructurescouplingutilities_27228',['DemStructuresCouplingUtilities',['../dc/d25/class_kratos_1_1_dem_structures_coupling_utilities.html',1,'Kratos']]],
  ['demthermalflags_27229',['DEMThermalFlags',['../d3/d9f/class_kratos_1_1_d_e_m_thermal_flags.html',1,'Kratos']]],
  ['demwrapper_27230',['DEMWrapper',['../dc/d13/classsolver__wrappers_1_1kratos_1_1dem__wrapper_1_1_d_e_m_wrapper.html',1,'solver_wrappers::kratos::dem_wrapper']]],
  ['denseeigenvaluesolver_27231',['DenseEigenvalueSolver',['../d1/d60/class_kratos_1_1_dense_eigenvalue_solver.html',1,'Kratos']]],
  ['densehouseholderqrdecomposition_27232',['DenseHouseholderQRDecomposition',['../d4/d05/class_kratos_1_1_dense_householder_q_r_decomposition.html',1,'Kratos']]],
  ['denselinearsolverfactory_27233',['DenseLinearSolverFactory',['../db/d49/class_dense_linear_solver_factory.html',1,'']]],
  ['denseqrdecomposition_27234',['DenseQRDecomposition',['../db/d82/class_kratos_1_1_dense_q_r_decomposition.html',1,'Kratos']]],
  ['denseqrdecomposition_3c_20tdensespace_20_3e_27235',['DenseQRDecomposition&lt; TDenseSpace &gt;',['../db/d82/class_kratos_1_1_dense_q_r_decomposition.html',1,'Kratos']]],
  ['densesingularvaluedecomposition_27236',['DenseSingularValueDecomposition',['../d7/df0/class_kratos_1_1_dense_singular_value_decomposition.html',1,'Kratos']]],
  ['densesingularvaluedecomposition_3c_20tdensespace_20_3e_27237',['DenseSingularValueDecomposition&lt; TDenseSpace &gt;',['../d7/df0/class_kratos_1_1_dense_singular_value_decomposition.html',1,'Kratos']]],
  ['densityfunction_27238',['DensityFunction',['../d1/dcb/class_kratos_1_1_density_function.html',1,'Kratos']]],
  ['densityfunctionnormal_27239',['DensityFunctionNormal',['../de/db8/class_kratos_1_1_density_function_normal.html',1,'Kratos']]],
  ['densityfunctionpolynomial_27240',['DensityFunctionPolynomial',['../db/d85/class_kratos_1_1_density_function_polynomial.html',1,'Kratos']]],
  ['deprecationmanager_27241',['DeprecationManager',['../d1/d8b/classdeprecation__management_1_1_deprecation_manager.html',1,'deprecation_management']]],
  ['depthintegrationinputprocess_27242',['DepthIntegrationInputProcess',['../dd/dfe/classdepth__integration__input__process_1_1_depth_integration_input_process.html',1,'depth_integration_input_process']]],
  ['depthintegrationoutputprocess_27243',['DepthIntegrationOutputProcess',['../d9/d0f/classdepth__integration__output__process_1_1_depth_integration_output_process.html',1,'depth_integration_output_process']]],
  ['depthintegrationprocess_27244',['DepthIntegrationProcess',['../d3/d72/class_depth_integration_process.html',1,'']]],
  ['derivative_27245',['Derivative',['../d7/ddd/class_kratos_1_1_q_s_v_m_s_derivative_utilities_1_1_derivative.html',1,'Kratos::QSVMSDerivativeUtilities']]],
  ['derivative_3c_200_20_3e_27246',['Derivative&lt; 0 &gt;',['../d7/ddd/class_kratos_1_1_q_s_v_m_s_derivative_utilities_1_1_derivative.html',1,'Kratos::QSVMSDerivativeUtilities']]],
  ['derivative_3c_20tcomponentindex_20_3e_27247',['Derivative&lt; TComponentIndex &gt;',['../d7/ddd/class_kratos_1_1_q_s_v_m_s_derivative_utilities_1_1_derivative.html',1,'Kratos::QSVMSDerivativeUtilities']]],
  ['derivativedata_27248',['DerivativeData',['../db/d37/class_kratos_1_1_derivative_data.html',1,'Kratos']]],
  ['derivativedata_3c_20tdim_2c_20tnumnodes_2c_20tnumnodes_20_3e_27249',['DerivativeData&lt; TDim, TNumNodes, TNumNodes &gt;',['../db/d37/class_kratos_1_1_derivative_data.html',1,'Kratos']]],
  ['derivativedatafrictional_27250',['DerivativeDataFrictional',['../d5/d9c/class_kratos_1_1_derivative_data_frictional.html',1,'Kratos']]],
  ['derivativerecoverystrategy_27251',['DerivativeRecoveryStrategy',['../da/def/classderivative__recovery_1_1derivative__recovery__strategy_1_1_derivative_recovery_strategy.html',1,'derivative_recovery::derivative_recovery_strategy']]],
  ['derivativesrecoverer_27252',['DerivativesRecoverer',['../d4/d08/classderivative__recovery_1_1recoverer_1_1_derivatives_recoverer.html',1,'derivative_recovery::recoverer']]],
  ['derivativesrecoveryprocess_27253',['DerivativesRecoveryProcess',['../d3/d42/classderivatives__recovery__process_1_1_derivatives_recovery_process.html',1,'derivatives_recovery_process']]],
  ['derivativesrecoveryutility_27254',['DerivativesRecoveryUtility',['../de/d9f/class_derivatives_recovery_utility.html',1,'']]],
  ['derivativesutilities_27255',['DerivativesUtilities',['../d1/d3a/class_derivatives_utilities.html',1,'']]],
  ['designlogger_27256',['DesignLogger',['../d6/d7d/classloggers_1_1design__logger__base_1_1_design_logger.html',1,'loggers::design_logger_base']]],
  ['designloggergid_27257',['DesignLoggerGID',['../d5/d0a/classloggers_1_1design__logger__gid_1_1_design_logger_g_i_d.html',1,'loggers::design_logger_gid']]],
  ['designloggerunv_27258',['DesignLoggerUNV',['../d4/d23/classloggers_1_1design__logger__unv_1_1_design_logger_u_n_v.html',1,'loggers::design_logger_unv']]],
  ['designloggervtk_27259',['DesignLoggerVTK',['../de/d93/classloggers_1_1design__logger__vtk_1_1_design_logger_v_t_k.html',1,'loggers::design_logger_vtk']]],
  ['det_27260',['det',['../d1/d12/interfacetensors_1_1det.html',1,'tensors']]],
  ['dev_27261',['dev',['../df/d52/interfacetensors_1_1dev.html',1,'tensors']]],
  ['diagonalpreconditioner_27262',['DiagonalPreconditioner',['../da/df4/class_kratos_1_1_diagonal_preconditioner.html',1,'Kratos']]],
  ['differentdatadifferenceresidual_27263',['DifferentDataDifferenceResidual',['../d2/dc9/classconvergence__accelerators_1_1convergence__accelerator__wrapper_1_1_different_data_difference_residual.html',1,'convergence_accelerators::convergence_accelerator_wrapper']]],
  ['differentialoperator_27264',['DifferentialOperator',['../d3/dc9/classderivatives__recovery__process_1_1_derivatives_recovery_process_1_1_differential_operator.html',1,'derivatives_recovery_process::DerivativesRecoveryProcess']]],
  ['directcopytransfer_27265',['DirectCopyTransfer',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20array_5f1d_3c_20double_2c_20tdim_20_3e_20_3e_27266',['DirectCopyTransfer&lt; array_1d&lt; double, TDim &gt; &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20bool_20_3e_27267',['DirectCopyTransfer&lt; bool &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20double_20_3e_27268',['DirectCopyTransfer&lt; double &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20int_20_3e_27269',['DirectCopyTransfer&lt; int &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20kratos_3a_3aflags_20_3e_27270',['DirectCopyTransfer&lt; Kratos::Flags &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directsolver_27271',['DirectSolver',['../df/dc7/class_kratos_1_1_direct_solver.html',1,'Kratos']]],
  ['directsolver_3c_20tsparsespacetype_2c_20tdensespacetype_2c_20reorderer_3c_20tsparsespacetype_2c_20tdensespacetype_20_3e_20_3e_27272',['DirectSolver&lt; TSparseSpaceType, TDenseSpaceType, Reorderer&lt; TSparseSpaceType, TDenseSpaceType &gt; &gt;',['../df/dc7/class_kratos_1_1_direct_solver.html',1,'Kratos']]],
  ['directsolver_3c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3aglobal_2c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_2c_20reorderer_3c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3aglobal_2c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_20_3e_20_3e_27273',['DirectSolver&lt; typename SpaceType&lt; typename TSolverType::Scalar &gt;::Global, typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local, Reorderer&lt; typename SpaceType&lt; typename TSolverType::Scalar &gt;::Global, typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local &gt; &gt;',['../df/dc7/class_kratos_1_1_direct_solver.html',1,'Kratos']]],
  ['directsolver_3c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_2c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_2c_20reorderer_3c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_2c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_20_3e_20_3e_27274',['DirectSolver&lt; typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local, typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local, Reorderer&lt; typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local, typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local &gt; &gt;',['../df/dc7/class_kratos_1_1_direct_solver.html',1,'Kratos']]],
  ['discontinuousshapefunctionsutilities_27275',['DiscontinuousShapeFunctionsUtilities',['../d7/d64/class_kratos_1_1_discontinuous_shape_functions_utilities.html',1,'Kratos']]],
  ['discontinuousshapefunctionsutilities_5f2d_27276',['DiscontinuousShapeFunctionsUtilities_2D',['../d4/d20/class_kratos_1_1_discontinuous_shape_functions_utilities__2_d.html',1,'Kratos']]],
  ['discreteparticleconfigure_27277',['DiscreteParticleConfigure',['../dc/dff/class_kratos_1_1_discrete_particle_configure.html',1,'Kratos']]],
  ['displacementcontactcriteria_27278',['DisplacementContactCriteria',['../d1/df2/class_kratos_1_1_displacement_contact_criteria.html',1,'Kratos']]],
  ['displacementcontrolcondition_27279',['DisplacementControlCondition',['../df/d64/class_displacement_control_condition.html',1,'']]],
  ['displacementcriteria_27280',['DisplacementCriteria',['../d3/d7f/class_kratos_1_1_displacement_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultipliercontactcriteria_27281',['DisplacementLagrangeMultiplierContactCriteria',['../d9/d87/class_kratos_1_1_displacement_lagrange_multiplier_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultiplierfrictionalcontactcriteria_27282',['DisplacementLagrangeMultiplierFrictionalContactCriteria',['../d2/dd3/class_kratos_1_1_displacement_lagrange_multiplier_frictional_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultipliermixedcontactcriteria_27283',['DisplacementLagrangeMultiplierMixedContactCriteria',['../d0/d61/class_kratos_1_1_displacement_lagrange_multiplier_mixed_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultipliermixedfrictionalcontactcriteria_27284',['DisplacementLagrangeMultiplierMixedFrictionalContactCriteria',['../d3/d27/class_kratos_1_1_displacement_lagrange_multiplier_mixed_frictional_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultiplierresidualcontactcriteria_27285',['DisplacementLagrangeMultiplierResidualContactCriteria',['../d0/dbc/class_kratos_1_1_displacement_lagrange_multiplier_residual_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultiplierresidualfrictionalcontactcriteria_27286',['DisplacementLagrangeMultiplierResidualFrictionalContactCriteria',['../d8/df9/class_kratos_1_1_displacement_lagrange_multiplier_residual_frictional_contact_criteria.html',1,'Kratos']]],
  ['displacementresidualcontactcriteria_27287',['DisplacementResidualContactCriteria',['../d8/db2/class_kratos_1_1_displacement_residual_contact_criteria.html',1,'Kratos']]],
  ['distancecalculationelementsimplex_27288',['DistanceCalculationElementSimplex',['../d7/d6e/class_kratos_1_1_distance_calculation_element_simplex.html',1,'Kratos']]],
  ['distancecalculator_27289',['DistanceCalculator',['../d9/d3e/class_kratos_1_1_distance_calculator.html',1,'Kratos']]],
  ['distancecalculator1_27290',['DistanceCalculator1',['../d5/d36/class_kratos_1_1_distance_calculator1.html',1,'Kratos']]],
  ['distanceimportutility_27291',['DistanceImportUtility',['../d8/da8/classread__distance__from__file_1_1_distance_import_utility.html',1,'read_distance_from_file']]],
  ['distancesmoothingelement_27292',['DistanceSmoothingElement',['../db/dad/class_kratos_1_1_distance_smoothing_element.html',1,'Kratos']]],
  ['distancespatialcontainersconditionconfigure_27293',['DistanceSpatialContainersConditionConfigure',['../da/d90/class_kratos_1_1_distance_spatial_containers_condition_configure.html',1,'Kratos']]],
  ['distancespatialcontainersconfigure_27294',['DistanceSpatialContainersConfigure',['../d1/d71/class_kratos_1_1_distance_spatial_containers_configure.html',1,'Kratos::DistanceSpatialContainersConfigure'],['../d0/d1c/class_kratos_1_1_internals_1_1_distance_spatial_containers_configure.html',1,'Kratos::Internals::DistanceSpatialContainersConfigure']]],
  ['distributedamgclcsrspmmutilities_27295',['DistributedAmgclCSRSpMMUtilities',['../d4/dee/class_kratos_1_1_distributed_amgcl_c_s_r_sp_m_m_utilities.html',1,'Kratos']]],
  ['distributedcsrmatrix_27296',['DistributedCsrMatrix',['../d7/d64/class_kratos_1_1_distributed_csr_matrix.html',1,'Kratos']]],
  ['distributedgidoutputprocess_27297',['DistributedGiDOutputProcess',['../da/d6d/classdistributed__gid__output__process_1_1_distributed_gi_d_output_process.html',1,'distributed_gid_output_process']]],
  ['distributedimportmodelpartutility_27298',['DistributedImportModelPartUtility',['../d9/d32/classdistributed__import__model__part__utility_1_1_distributed_import_model_part_utility.html',1,'distributed_import_model_part_utility']]],
  ['distributedmodelpartinitializer_27299',['DistributedModelPartInitializer',['../dd/db3/class_kratos_1_1_distributed_model_part_initializer.html',1,'Kratos']]],
  ['distributednumbering_27300',['DistributedNumbering',['../da/da4/class_kratos_1_1_distributed_numbering.html',1,'Kratos']]],
  ['distributednumbering_3c_20indextype_20_3e_27301',['DistributedNumbering&lt; IndexType &gt;',['../da/da4/class_kratos_1_1_distributed_numbering.html',1,'Kratos']]],
  ['distributednumbering_3c_20std_3a_3asize_5ft_20_3e_27302',['DistributedNumbering&lt; std::size_t &gt;',['../da/da4/class_kratos_1_1_distributed_numbering.html',1,'Kratos']]],
  ['distributedrestartutility_27303',['DistributedRestartUtility',['../d4/d2d/classdistributed__restart__utility_1_1_distributed_restart_utility.html',1,'distributed_restart_utility']]],
  ['distributedsparsegraph_27304',['DistributedSparseGraph',['../d2/dcc/class_kratos_1_1_distributed_sparse_graph.html',1,'Kratos']]],
  ['distributedsystemvector_27305',['DistributedSystemVector',['../df/dcf/class_kratos_1_1_distributed_system_vector.html',1,'Kratos']]],
  ['distributedvectorexporter_27306',['DistributedVectorExporter',['../db/d00/class_kratos_1_1_distributed_vector_exporter.html',1,'Kratos']]],
  ['distributedvectorexporter_3c_20std_3a_3asize_5ft_20_3e_27307',['DistributedVectorExporter&lt; std::size_t &gt;',['../db/d00/class_kratos_1_1_distributed_vector_exporter.html',1,'Kratos']]],
  ['distributedvectorimporter_27308',['DistributedVectorImporter',['../d4/d23/class_kratos_1_1_distributed_vector_importer.html',1,'Kratos']]],
  ['distributepointvaluesoperation_27309',['DistributePointValuesOperation',['../dc/d46/classcoupling__operations_1_1distribute__point__values_1_1_distribute_point_values_operation.html',1,'coupling_operations::distribute_point_values']]],
  ['divergencefreerefinementprocess_27310',['DivergenceFreeRefinementProcess',['../d4/de1/classdivergencefree__refinement__process_1_1_divergence_free_refinement_process.html',1,'divergencefree_refinement_process']]],
  ['division_27311',['Division',['../dc/d2a/struct_kratos_1_1_binary_operations_1_1_division.html',1,'Kratos::BinaryOperations']]],
  ['dof_27312',['Dof',['../dc/d58/class_kratos_1_1_dof.html',1,'Kratos']]],
  ['dof_5fiterator_5fequal_27313',['dof_iterator_equal',['../dd/d0b/struct_kratos_1_1_block_builder_and_solver_1_1dof__iterator__equal.html',1,'Kratos::BlockBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::dof_iterator_equal'],['../d7/d15/struct_kratos_1_1_reduction_builder_and_solver_1_1dof__iterator__equal.html',1,'Kratos::ReductionBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::dof_iterator_equal']]],
  ['dof_5fiterator_5fhash_27314',['dof_iterator_hash',['../d1/d5d/struct_kratos_1_1_block_builder_and_solver_1_1dof__iterator__hash.html',1,'Kratos::BlockBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::dof_iterator_hash'],['../dd/d96/struct_kratos_1_1_reduction_builder_and_solver_1_1dof__iterator__hash.html',1,'Kratos::ReductionBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::dof_iterator_hash']]],
  ['dofidaccess_27315',['DofIdAccess',['../df/d56/class_kratos_1_1_m_p_i_internals_1_1_dof_id_access.html',1,'Kratos::MPIInternals']]],
  ['dofpointercomparor_27316',['DofPointerComparor',['../d7/dbc/struct_kratos_1_1_dof_pointer_comparor.html',1,'Kratos']]],
  ['dofpointerhasher_27317',['DofPointerHasher',['../df/dc1/struct_kratos_1_1_dof_pointer_hasher.html',1,'Kratos']]],
  ['dofscriterion_27318',['DofsCriterion',['../d8/d29/class_kratos_1_1_dofs_criterion.html',1,'Kratos']]],
  ['doftrait_27319',['DofTrait',['../dc/d06/struct_kratos_1_1_dof_trait.html',1,'Kratos']]],
  ['dofupdater_27320',['DofUpdater',['../d3/d3f/class_kratos_1_1_dof_updater.html',1,'Kratos']]],
  ['domain_27321',['Domain',['../d1/d20/classcore_1_1xdmf_1_1_domain.html',1,'core::xdmf']]],
  ['domainentitiesidcontainer_27322',['DomainEntitiesIdContainer',['../d5/d75/class_kratos_1_1_morton_divide_input_to_partitions_process_1_1_domain_entities_id_container.html',1,'Kratos::MortonDivideInputToPartitionsProcess']]],
  ['domainpanel2d_27323',['DomainPanel2D',['../de/dee/classprojection__utilities_1_1_domain_panel2_d.html',1,'projection_utilities']]],
  ['domainpanel3d_27324',['DomainPanel3D',['../d5/d16/classprojection__utilities_1_1_domain_panel3_d.html',1,'projection_utilities']]],
  ['domainutilities_27325',['DomainUtilities',['../dc/d27/classdomain__utilities_1_1_domain_utilities.html',1,'domain_utilities']]],
  ['doubleaugmentedlagrangianmethodfrictionlessmortarcontactcondition_27326',['DoubleAugmentedLagrangianMethodFrictionlessMortarContactCondition',['../d2/dc4/class_double_augmented_lagrangian_method_frictionless_mortar_contact_condition.html',1,'']]],
  ['dpgvms_27327',['DPGVMS',['../d7/d1a/class_kratos_1_1_d_p_g_v_m_s.html',1,'Kratos']]],
  ['dragresponsefunction_27328',['DragResponseFunction',['../d3/de1/class_kratos_1_1_drag_response_function.html',1,'Kratos']]],
  ['dropletdynamicsanalysis_27329',['DropletDynamicsAnalysis',['../d3/d17/classdroplet__dynamics__analysis_1_1_droplet_dynamics_analysis.html',1,'droplet_dynamics_analysis']]],
  ['dropletdynamicselement_27330',['DropletDynamicsElement',['../db/da2/class_kratos_1_1_droplet_dynamics_element.html',1,'Kratos']]],
  ['dropletdynamicssolver_27331',['DropletDynamicsSolver',['../d3/d72/classdroplet__dynamics__solver_1_1_droplet_dynamics_solver.html',1,'droplet_dynamics_solver']]],
  ['druckerpragerplasticpotential_27332',['DruckerPragerPlasticPotential',['../d1/da5/class_kratos_1_1_drucker_prager_plastic_potential.html',1,'Kratos']]],
  ['druckerprageryieldsurface_27333',['DruckerPragerYieldSurface',['../d5/d72/class_kratos_1_1_drucker_prager_yield_surface.html',1,'Kratos']]],
  ['duallagrangemultiplieroperators_27334',['DualLagrangeMultiplierOperators',['../de/d18/class_kratos_1_1_dual_lagrange_multiplier_operators.html',1,'Kratos']]],
  ['duallagrangemultiplieroperators_3c_20tnumnodes_2c_20tnumnodes_20_3e_27335',['DualLagrangeMultiplierOperators&lt; TNumNodes, TNumNodes &gt;',['../de/d18/class_kratos_1_1_dual_lagrange_multiplier_operators.html',1,'Kratos']]],
  ['duallagrangemultiplieroperatorswithderivatives_27336',['DualLagrangeMultiplierOperatorsWithDerivatives',['../d2/de0/class_kratos_1_1_dual_lagrange_multiplier_operators_with_derivatives.html',1,'Kratos']]],
  ['dummyio_27337',['DummyIO',['../db/d0f/classsolver__wrappers_1_1dummy__io_1_1_dummy_i_o.html',1,'solver_wrappers::dummy_io']]],
  ['dummysolverwrapper_27338',['DummySolverWrapper',['../d9/d0b/classhelpers_1_1dummy__solver__wrapper_1_1_dummy_solver_wrapper.html',1,'helpers::dummy_solver_wrapper']]],
  ['dvms_27339',['DVMS',['../dc/d6e/class_kratos_1_1_d_v_m_s.html',1,'Kratos']]],
  ['dvmsdemcoupled_27340',['DVMSDEMCoupled',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dynamicarraytypetransfer_27341',['DynamicArrayTypeTransfer',['../d9/d1c/struct_kratos_1_1_m_p_i_internals_1_1_dynamic_array_type_transfer.html',1,'Kratos::MPIInternals']]],
  ['dynamicarraytypetransfer_3c_20matrix_20_3e_27342',['DynamicArrayTypeTransfer&lt; Matrix &gt;',['../d9/d1c/struct_kratos_1_1_m_p_i_internals_1_1_dynamic_array_type_transfer.html',1,'Kratos::MPIInternals']]],
  ['dynamicarraytypetransfer_3c_20vector_20_3e_27343',['DynamicArrayTypeTransfer&lt; Vector &gt;',['../d9/d1c/struct_kratos_1_1_m_p_i_internals_1_1_dynamic_array_type_transfer.html',1,'Kratos::MPIInternals']]],
  ['dynamicscheme_27344',['DynamicScheme',['../db/d8f/class_kratos_1_1_dynamic_scheme.html',1,'Kratos']]],
  ['dynamicsmagorinsky_27345',['DynamicSmagorinsky',['../d3/d3f/classdynamic__smagorinsky__utilities_1_1_dynamic_smagorinsky.html',1,'dynamic_smagorinsky_utilities']]],
  ['dynamicsmagorinskyutils_27346',['DynamicSmagorinskyUtils',['../d7/dd1/class_kratos_1_1_dynamic_smagorinsky_utils.html',1,'Kratos']]],
  ['dynamicvms_27347',['DynamicVMS',['../de/d8f/class_kratos_1_1_dynamic_v_m_s.html',1,'Kratos']]]
];
